export default ActionCodes = {
  UPDATE_APP_STATES: "UPDATE_APP_STATES",
  RECEIVE_NOTIFICATION_TOKEN: "RECEIVE_NOTIFICATION_TOKEN",
  LOGGED_IN_TO_FACEBOOK: "LOGGED_IN_TO_FACEBOOK",
  LOGOUT: "LOGOUT",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_CURRENT_LANGUAGE: "SET_CURRENT_LANGUAGE",
};
